//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduCarePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public System.Guid FileID { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string ContentDetails { get; set; }
        public string ContentURL { get; set; }
        public System.DateTime UploadDate { get; set; }
        public System.Guid LessionID { get; set; }
    
        public virtual Lesson Lesson { get; set; }
    }
}
