//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduCarePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizResult
    {
        public System.Guid ResultID { get; set; }
        public double ScoreObtained { get; set; }
        public System.Guid QuizID { get; set; }
        public System.Guid StudentID { get; set; }
        public System.DateTime AssessmentDate { get; set; }
        public double TotalMarks { get; set; }
        public double Percentage { get; set; }
    
        public virtual Quizze Quizze { get; set; }
        public virtual Student Student { get; set; }
    }
}
