//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduCarePortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutorial
    {
        public int TutorialID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Tutorial_URL { get; set; }
        public string Transcript { get; set; }
        public int SubjectID { get; set; }
    }
}
